spring:
  application:
    name: store
  profiles:
    active: dev
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 900 #15
  refreshTokenExpiration: 604800 #7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
