-- Insert Categories
INSERT INTO categories (name)
VALUES ('Fruits'),
       ('Vegetables'),
       ('Dairy'),
       ('Bakery'),
       ('Beverages'),
       ('Snacks'),
       ('Rice & Grains'),
       ('Cooking Essentials'),
       ('Frozen Foods'),
       ('Personal Care');

-- Insert Products
INSERT INTO products (name, price, description, category_id)
VALUES ('Fresh Bananas (1 Dozen)',
        79.00,
        'Naturally sweet and rich in potassium. Perfect for breakfast, smoothies, and healthy snacks.',
        1),
       ('Tomatoes (1 kg)',
        49.00,
        'Fresh farm-picked tomatoes ideal for curries, salads, and sauces.',
        2),
       ('Amul Gold Milk (1L)',
        68.00,
        'Full cream pasteurized milk suitable for tea, coffee, and daily consumption.',
        3),
       ('Harvest Gold Whole Wheat Bread',
        45.00,
        'Soft whole wheat bread made with high-quality grains for a healthy breakfast.',
        4),
       ('Tropicana Orange Juice (1L)',
        120.00,
        '100% orange juice with no added preservatives, rich in Vitamin C.',
        5),
       ('Lay''s Classic Salted Chips (52g)',
        20.00,
        'Crispy potato chips lightly seasoned with salt for the perfect snack.',
        6),
       ('India Gate Basmati Rice (5 kg)',
        699.00,
        'Premium aged basmati rice with long grains and rich aroma.',
        7),
       ('Fortune Sunlite Refined Sunflower Oil (1L)',
        179.00,
        'Light refined sunflower oil suitable for everyday cooking and frying.',
        8),
       ('McCain French Fries (750g)',
        165.00,
        'Frozen crispy French fries ready to bake, fry, or air fry.',
        9),
       ('Colgate Strong Teeth Toothpaste (200g)',
        118.00,
        'Fluoride toothpaste that helps strengthen teeth and protects against cavities.',
        10);